{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7dd4a930",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[WDM] - \n",
      "\n",
      "[WDM] - ====== WebDriver manager ======\n",
      "[WDM] - Current google-chrome version is 113.0.5672\n",
      "[WDM] - Get LATEST driver version for 113.0.5672\n",
      "[WDM] - Driver [/Users/gaignard-a/.wdm/drivers/chromedriver/mac64/113.0.5672.63/chromedriver] found in cache\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "sys.path.append(\"../\")\n",
    "\n",
    "from rdflib import ConjunctiveGraph, URIRef\n",
    "import requests\n",
    "from requests.exceptions import InvalidURL\n",
    "import random\n",
    "import json\n",
    "from tqdm.notebook import tqdm\n",
    "import pandas as pd\n",
    "from metrics.WebResource import WebResource"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "d035e081",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_live_deploys_urls():\n",
    "    results = []\n",
    "    live_deploys_remote_file = \"https://raw.githubusercontent.com/BioSchemas/bioschemas.github.io/master/_data/live_deployments.json\"\n",
    "    res = requests.get(live_deploys_remote_file)\n",
    "    live_deploys = res.json()\n",
    "    \n",
    "    for r in live_deploys[\"resources\"]:\n",
    "        for p in r[\"profiles\"]:\n",
    "            if \"exampleURL\" in p.keys():\n",
    "                results.append(p[\"exampleURL\"])\n",
    "            else : \n",
    "                print(f\"no example URL for profile {p['profileName']} and url {r['url']}\")\n",
    "    print(f\"found {len(set(results))} live deploys\")\n",
    "    return list(set(results))\n",
    "\n",
    "\n",
    "\n",
    "def test_ld_bioschemas_annot():\n",
    "        res = get_live_deploys_urls()\n",
    "        errors = []\n",
    "        results = []\n",
    "        \n",
    "        i = 0\n",
    "        for r in tqdm(res):\n",
    "        #for r in reversed(res):\n",
    "            row = {}\n",
    "            status_code = requests.head(r).status_code\n",
    "            print(r)\n",
    "            row['url'] = r\n",
    "            print(\"Status code: \" + str(status_code))\n",
    "            row['status code'] = str(status_code)\n",
    "            try :\n",
    "                kg = WebResource(r).get_rdf()\n",
    "                print(\"Triples: \" + str(len(kg)))\n",
    "                row['Retrieved triples'] = len(kg)\n",
    "                if not len(kg) > 0:\n",
    "                    print(f\"# Error with {r}\")\n",
    "                    row['Error'] = True\n",
    "                    errors.append(r)\n",
    "            except UnicodeDecodeError as err:\n",
    "                print(err)\n",
    "            results.append(row)\n",
    "\n",
    "        print(f\"{len(res)} tested URLS\")\n",
    "        print(f\"{len(errors)} failing URLS\")\n",
    "        print(errors)\n",
    "        df = pd.read_json(json.dumps(results))\n",
    "        return df\n",
    "    \n",
    "def retrieve_bioschemas(url):  \n",
    "    #FC_get_md = \"https://fair-checker.france-bioinformatique.fr/api/inspect/get_rdf_metadata\"\n",
    "    FC_get_md = \"http://localhost:5000/api/inspect/get_rdf_metadata\"\n",
    "    kg = ConjunctiveGraph()\n",
    "    res = requests.get(url=FC_get_md, params={\"url\": url})\n",
    "    try:\n",
    "        kg.parse(data=res.text, format=\"json-ld\")\n",
    "    except Exception as e:\n",
    "            print(e)\n",
    "    print(f\"Loaded {len(kg)} RDF triples from {url}\")\n",
    "    return kg\n",
    "\n",
    "def check_bioschemas(url):  \n",
    "    #FC_bs_valid = \"https://fair-checker.france-bioinformatique.fr/api/inspect/bioschemas_validation\"\n",
    "    #FC_bs_valid = \"https://fair-checker.france-bioinformatique.fr/api/inspect/bioschemas_validation_by_conformsto\"\n",
    "    FC_bs_valid = \"http://localhost:5000/api/inspect/bioschemas_validation_by_conformsto\"\n",
    "    res = requests.get(url=FC_bs_valid, params={\"url\": url})\n",
    "    #print(res.text)\n",
    "    #try:\n",
    "    #    print(json.dumps(res.json(), indent=True))\n",
    "    #except Exception as e:\n",
    "    #    print(e)\n",
    "    return res.json()\n",
    "\n",
    "def has_conforms_to(kg):\n",
    "    conformsTo = URIRef(\"http://purl.org/dc/terms/conformsTo\")\n",
    "    return (None, conformsTo, None) in kg"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca494b2e",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d2dbb0af",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "found 136 live deploys\n",
      "retrieved 136 live deploys\n"
     ]
    }
   ],
   "source": [
    "lds = get_live_deploys_urls()\n",
    "#lds = random.sample(lds,20)\n",
    "print(f\"retrieved {len(lds)} live deploys\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 188,
   "id": "2c8803f6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "b33a1310f68f4bd7a9c8c841db4d34ef",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/136 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loaded 14 RDF triples from https://bridgedb.github.io/data/gene_database/\n",
      "Loaded 95 RDF triples from http://itsonedb.cloud.ba.infn.it/\n",
      "Loaded 124 RDF triples from https://www.sib.swiss/training/course/20230426_DOCK\n",
      "Loaded 0 RDF triples from https://proteinensemble.org/PED00014\n",
      "Loaded 25 RDF triples from https://bioregistry.io/registry/hgnc\n",
      "Loaded 373 RDF triples from https://humanmine.org/\n",
      "Loaded 17 RDF triples from https://modelarchive.org/\n",
      "Loaded 13 RDF triples from https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=141189&lng=en\n",
      "Loaded 0 RDF triples from https://deb-central.org/\n",
      "Loaded 34 RDF triples from https://bio.tools/blast\n",
      "Loaded 10 RDF triples from https://scholia.toolforge.org/chemical/Q18216\n",
      "Loaded 36 RDF triples from https://bmrb.io/data_library/summary/index.php?bmrbId=30309\n",
      "Loaded 26 RDF triples from https://bioschemas.org/tutorials/what_why_bioschemas\n",
      "Loaded 0 RDF triples from https://proteinensemble.org/\n",
      "Loaded 28 RDF triples from http://edgar.biocomp.unibo.it/\n",
      "Loaded 8 RDF triples from https://www.alliancegenome.org/gene/MGI:2442292\n",
      "Loaded 23 RDF triples from https://datacatalog.elixir-luxembourg.org/e/dataset/924dfe7a-71e8-11eb-bafe-3e22fbb3883f\n",
      "Loaded 71 RDF triples from https://www.metanetx.org/chem_info/MNXM680\n",
      "Loaded 32 RDF triples from https://nanocommons.github.io/tutorials/enteringData\n",
      "Loaded 69 RDF triples from https://zbmed.github.io/damalos/\n",
      "Loaded 48 RDF triples from https://swissmodel.expasy.org/\n",
      "Loaded 12 RDF triples from https://bridgedb.github.io/\n",
      "Loaded 16 RDF triples from https://www.birmingham.ac.uk/facilities/metabolomics-training-centre/courses/q-exactive.aspx\n",
      "Loaded 46 RDF triples from https://www.metanetx.org/\n",
      "Loaded 32 RDF triples from https://enanomapper.github.io/tutorials/Entering_and_analysing_nano_safety_data/readme.html\n",
      "Loaded 12 RDF triples from https://workflowhub.eu/\n",
      "Loaded 51 RDF triples from https://mint.bio.uniroma2.it/\n",
      "Loaded 12 RDF triples from https://bio.tools/covidmine\n",
      "Loaded 8 RDF triples from https://cancer.sanger.ac.uk/cosmic/\n",
      "Loaded 54 RDF triples from https://disprot.org/DP00086r026\n",
      "Loaded 77 RDF triples from https://www.covid19dataportal.org/\n",
      "Loaded 14 RDF triples from https://h2020-riskgone.github.io/riskgone-materials/identifiers_and_guidance.html\n",
      "Loaded 8 RDF triples from https://www.alliancegenome.org/gene/RGD:620474\n",
      "Loaded 49 RDF triples from https://workflowhub.eu/workflows/18\n",
      "Loaded 49 RDF triples from https://string-db.org/network/9606.ENSP00000379258\n",
      "Loaded 41 RDF triples from https://bgee.org/?page=species&amp;species_id=9606#expr-calls\n",
      "Loaded 15 RDF triples from https://prosite.expasy.org\n",
      "Loaded 1 RDF triples from http://www.ebi.ac.uk/pdbe/entry/pdb/4a7l\n",
      "Loaded 12 RDF triples from https://pathvisio.org/\n",
      "Loaded 52 RDF triples from https://fairsharing.org/\n",
      "Loaded 43 RDF triples from https://bar.biocomp.unibo.it/bar3/\n",
      "Loaded 36 RDF triples from https://pcddb.cryst.bbk.ac.uk/\n",
      "Loaded 19 RDF triples from https://www.ebi.ac.uk/biosamples/\n",
      "Loaded 13 RDF triples from https://massbank.eu/MassBank/RecordDisplay?id=LQB00001&dsn=RIKEN_IMS\n",
      "Loaded 40 RDF triples from https://pairedomicsdata.bioinformatics.nl/projects/d0f1add5-5b16-4f78-9b93-0d1d9c9bcb59.1\n",
      "Loaded 46 RDF triples from https://tess.elixir-europe.org/materials/hands-on-for-exome-sequencing-data-analysis-for-diagnosing-a-genetic-disease-tutorial\n",
      "Loaded 214 RDF triples from https://www.ebi.ac.uk/interpro/\n",
      "Loaded 43 RDF triples from https://cells.ebisc.org/BIHi006-D\n",
      "Loaded 73 RDF triples from https://rdmkit.elixir-europe.org/human_data.html\n",
      "Loaded 64 RDF triples from https://disprot.org/\n",
      "Loaded 37 RDF triples from https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:37133\n",
      "Loaded 0 RDF triples from https://aip.fipapatients.org/\n",
      "Loaded 0 RDF triples from https://www.opalesurfcasting.net/connaissances/faune-et-flore/le-saumon-de-l-atlantique-salmo-salar.html\n",
      "Loaded 11 RDF triples from https://ippidb.pasteur.fr/\n",
      "Loaded 0 RDF triples from https://flymine.org/\n",
      "Loaded 36 RDF triples from https://tess.elixir-europe.org/events/introduction-to-r-for-biologists-online\n",
      "Loaded 8 RDF triples from https://zbmed.github.io/damalos/docs/2020.html\n",
      "Loaded 37 RDF triples from https://www.genenames.org/data/gene-symbol-report/#data-set\n",
      "Loaded 0 RDF triples from https://www.proteinatlas.org/\n",
      "Loaded 56 RDF triples from http://mvid-central.org/\n",
      "Loaded 763 RDF triples from https://disprot.org/DP00086\n",
      "Loaded 69 RDF triples from https://mobidb.org/\n",
      "Loaded 41 RDF triples from https://bgee.org/\n",
      "Loaded 49 RDF triples from https://www.chd7.org/\n",
      "Loaded 0 RDF triples from https://www.metanetx.org/ftp/\n",
      "Loaded 47 RDF triples from https://hpscreg.eu/cell-line/BIHi006-D\n",
      "Loaded 1 RDF triples from https://synbiohub.org/public/igem/BBa_K165005/1\n",
      "Loaded 37 RDF triples from https://ega-archive.org/\n",
      "Loaded 0 RDF triples from http://159.149.160.88/cscan\n",
      "Loaded 15 RDF triples from https://hamap.expasy.org/cgi-bin/unirule/unirule_browse.cgi\n",
      "Loaded 1 RDF triples from https://www.ebi.ac.uk/pdbe/entry/pdb/5hbi/protein/1\n",
      "Loaded 260 RDF triples from http://edgar.biocomp.unibo.it/cgi-bin/gene_disease_db/gene.py?gene=A2M\n",
      "Loaded 7 RDF triples from https://nanocommons.github.io/specifications/jrc/\n",
      "Loaded 85 RDF triples from https://www.gbif.org/dataset/c0cc29de-f49f-4b66-b4ec-c83afbb7101d\n",
      "Loaded 1 RDF triples from https://synbiohub.org/\n",
      "Loaded 28 RDF triples from https://pairedomicsdata.bioinformatics.nl/\n",
      "Loaded 7 RDF triples from https://www.guidetopharmacology.org/coronavirus.jsp\n",
      "Loaded 171 RDF triples from https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.html\n",
      "Loaded 0 RDF triples from https://www.ebi.ac.uk/biosamples/samples/SAMEA491372\n",
      "Loaded 0 RDF triples from https://galaxyproject.org/events/\n",
      "Loaded 18 RDF triples from https://datacatalog.elixir-luxembourg.org/\n",
      "Loaded 7 RDF triples from https://scholia.toolforge.org/taxon/Q15978631\n",
      "Loaded 21 RDF triples from https://ega-archive.org/studies/EGAS00000000001\n",
      "Loaded 28 RDF triples from http://phenpath.biocomp.unibo.it/cgi-bin/phenpath/ppDB.py\n",
      "Loaded 26 RDF triples from https://nanocommons.github.io/datasets/\n",
      "Loaded 0 RDF triples from https://datamed.org/display-item.php?repository=0006&id=59139ef65152c62a9fc18ff7\n",
      "Loaded 7 RDF triples from https://bigcat-um.github.io/BiGCaT-Teaching/\n",
      "Invalid url: http://\n",
      "Loaded 78 RDF triples from https://www.ebi.ac.uk/interpro/entry/InterPro/IPR015252/\n",
      "Loaded 0 RDF triples from https://www.ensembl.org/id/ENSG00000139618\n",
      "Loaded 29 RDF triples from https://pcddb.cryst.bbk.ac.uk/deposit/CD0000031000\n",
      "Loaded 9 RDF triples from https://www.uniprot.org/uniprot/\n",
      "Loaded 0 RDF triples from https://ippidb.pasteur.fr/compounds/1103#compound\n",
      "Loaded 37 RDF triples from https://www.genenames.org/#data-catalog\n",
      "Loaded 77 RDF triples from https://www.ebi.ac.uk/training/events/metagenomics-bioinformatics-2022/\n",
      "Loaded 55 RDF triples from https://bioinformatics.ca/workshops-all/2021-infectious-disease-epidemiology-analysis/\n",
      "Loaded 14 RDF triples from https://hamap.expasy.org/archaea.html\n",
      "Loaded 12 RDF triples from https://www.ebi.ac.uk/Tools/hmmer/search/phmmer\n",
      "Loaded 8 RDF triples from https://biopragmatics.github.io/bioversions/\n",
      "Loaded 14 RDF triples from https://enzyme.expasy.org/EC/1.1.3.-\n",
      "Loaded 15 RDF triples from https://training.galaxyproject.org/training-material/hall-of-fame/hexylena/\n",
      "Loaded 14 RDF triples from http://gigadb.org/site/index\n",
      "Loaded 11 RDF triples from https://corkoakdb.org/gene/13014\n",
      "Loaded 213 RDF triples from https://swissmodel.expasy.org/repository\n",
      "Loaded 19 RDF triples from https://workflowhub.eu/people/9\n",
      "Loaded 132 RDF triples from https://www.ebi.ac.uk/chembl/\n",
      "Loaded 4 RDF triples from https://search.data.enanomapper.net/about/enanomapper/\n",
      "Loaded 54 RDF triples from https://reactome.org/content/detail/R-HSA-449147\n",
      "Loaded 12 RDF triples from https://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=8299\n",
      "Loaded 5 RDF triples from https://bgee.org/?page=gene&gene_id=ENSG00000274928\n",
      "Loaded 7 RDF triples from https://scholia.toolforge.org/protein/Q424728\n",
      "Loaded 0 RDF triples from http://159.149.160.88/pscan/\n",
      "Loaded 143 RDF triples from https://www.sib.swiss/training/course/20221123_OPEMP\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loaded 20 RDF triples from https://www.elixir-europe.org/events/biohackathon-2018-paris\n",
      "Expecting value: line 1 column 1 (char 0)\n",
      "Loaded 0 RDF triples from https://pippa.psb.ugent.be/pippa_experiments/consult_experiment_basic_info/55\n",
      "Loaded 10 RDF triples from https://psnpbind.org/protein/1owh\n",
      "Loaded 44 RDF triples from http://www.cathdb.info\n",
      "Loaded 0 RDF triples from https://wikipathways.org/\n",
      "Loaded 35 RDF triples from https://bioschemas.org/meetings/2022-01_SWAT4HCLS_leiden\n",
      "Loaded 19 RDF triples from https://www.omicsdi.org/#/dataset/arrayexpress-repository/E-MTAB-6848\n",
      "Loaded 0 RDF triples from https://www.gbif.org/species/5220113\n",
      "Loaded 48 RDF triples from http://phenpath.biocomp.unibo.it/phenpath/\n",
      "Loaded 0 RDF triples from http://159.149.160.88/pscan_chip_dev/\n",
      "Loaded 27 RDF triples from https://identifiers.org/\n",
      "Loaded 31 RDF triples from https://www.ensembl.org/\n",
      "Loaded 49 RDF triples from https://zbmed-semtec.github.io/dome-galaxy-training/docs/DOME.html\n",
      "Loaded 46 RDF triples from https://zbmed-semtec.github.io/BioMedSem-IR-KD/docs/Lesson1.html\n",
      "Loaded 8 RDF triples from https://scholia.toolforge.org/gene/Q18030793\n",
      "Loaded 77 RDF triples from https://mobidb.org/P04637\n",
      "Loaded 0 RDF triples from https://www.france-bioinformatique.fr/en/evenements_upcoming\n",
      "Loaded 247 RDF triples from https://inpn.mnhn.fr/espece/cd_nom/60878/\n",
      "Loaded 44 RDF triples from https://www.guidetopharmacology.org/\n",
      "Loaded 182 RDF triples from https://string-db.org/\n",
      "Loaded 25 RDF triples from https://ega-archive.org/datasets/EGAD00000000001\n",
      "Loaded 35 RDF triples from https://tess.elixir-europe.org/events/1st-international-conference-on-fair-digital-objects-fdo2022\n",
      "Loaded 50 RDF triples from https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL59/\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>URL</th>\n",
       "      <th>HTTP_status</th>\n",
       "      <th>nb_triples</th>\n",
       "      <th>has_conforms_to</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>https://bridgedb.github.io/data/gene_database/</td>\n",
       "      <td>301.0</td>\n",
       "      <td>14.0</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>http://itsonedb.cloud.ba.infn.it/</td>\n",
       "      <td>200.0</td>\n",
       "      <td>95.0</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>https://www.sib.swiss/training/course/20230426...</td>\n",
       "      <td>200.0</td>\n",
       "      <td>124.0</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>https://proteinensemble.org/PED00014</td>\n",
       "      <td>200.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>https://bioregistry.io/registry/hgnc</td>\n",
       "      <td>200.0</td>\n",
       "      <td>25.0</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>131</th>\n",
       "      <td>https://www.guidetopharmacology.org/</td>\n",
       "      <td>200.0</td>\n",
       "      <td>44.0</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>132</th>\n",
       "      <td>https://string-db.org/</td>\n",
       "      <td>200.0</td>\n",
       "      <td>182.0</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>133</th>\n",
       "      <td>https://ega-archive.org/datasets/EGAD00000000001</td>\n",
       "      <td>200.0</td>\n",
       "      <td>25.0</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>134</th>\n",
       "      <td>https://tess.elixir-europe.org/events/1st-inte...</td>\n",
       "      <td>200.0</td>\n",
       "      <td>35.0</td>\n",
       "      <td>True</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>135</th>\n",
       "      <td>https://www.ebi.ac.uk/chembl/compound_report_c...</td>\n",
       "      <td>200.0</td>\n",
       "      <td>50.0</td>\n",
       "      <td>False</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>136 rows × 4 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                   URL  HTTP_status  \\\n",
       "0       https://bridgedb.github.io/data/gene_database/        301.0   \n",
       "1                    http://itsonedb.cloud.ba.infn.it/        200.0   \n",
       "2    https://www.sib.swiss/training/course/20230426...        200.0   \n",
       "3                 https://proteinensemble.org/PED00014        200.0   \n",
       "4                 https://bioregistry.io/registry/hgnc        200.0   \n",
       "..                                                 ...          ...   \n",
       "131               https://www.guidetopharmacology.org/        200.0   \n",
       "132                             https://string-db.org/        200.0   \n",
       "133   https://ega-archive.org/datasets/EGAD00000000001        200.0   \n",
       "134  https://tess.elixir-europe.org/events/1st-inte...        200.0   \n",
       "135  https://www.ebi.ac.uk/chembl/compound_report_c...        200.0   \n",
       "\n",
       "     nb_triples has_conforms_to  \n",
       "0          14.0            True  \n",
       "1          95.0           False  \n",
       "2         124.0            True  \n",
       "3           0.0           False  \n",
       "4          25.0            True  \n",
       "..          ...             ...  \n",
       "131        44.0           False  \n",
       "132       182.0            True  \n",
       "133        25.0           False  \n",
       "134        35.0            True  \n",
       "135        50.0           False  \n",
       "\n",
       "[136 rows x 4 columns]"
      ]
     },
     "execution_count": 188,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "rows = []\n",
    "i = 0\n",
    "for ld in tqdm(lds):\n",
    "    row = {\"URL\": ld}    \n",
    "    try :\n",
    "        status_code = requests.head(ld).status_code\n",
    "        row[\"HTTP_status\"] = status_code\n",
    "        kg = retrieve_bioschemas(ld)\n",
    "        #print(kg.serialize(format=\"ntriples\"))\n",
    "        row[\"nb_triples\"] = len(kg)\n",
    "        row[\"has_conforms_to\"] = has_conforms_to(kg)\n",
    "    except InvalidURL as e :\n",
    "        print(f\"Invalid url: {ld}\")\n",
    "    rows.append(row)\n",
    "    \n",
    "df1 = pd.DataFrame.from_records(rows)\n",
    "df1.to_csv(\"bioschemas_harvesting.csv\")\n",
    "df1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f65bfb5e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "d9027674",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "9b669ab05bd443ec8b6ed6d9e53812cb",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "  0%|          | 0/136 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error while validating https://workflowhub.eu/workflows/18\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://bio.tools/blast\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://zbmed-semtec.github.io/BioMedSem-IR-KD/docs/Lesson1.html\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://pathvisio.org/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating http://gigadb.org/site/index\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://www.uniprot.org/uniprot/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://scholia.toolforge.org/taxon/Q15978631\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://www.alliancegenome.org/gene/MGI:2442292\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://swissmodel.expasy.org/repository\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://ega-archive.org/studies/EGAS00000000001\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://mobidb.org/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://hpscreg.eu/cell-line/BIHi006-D\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://scholia.toolforge.org/chemical/Q18216\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://www.alliancegenome.org/gene/RGD:620474\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://ippidb.pasteur.fr/compounds/1103#compound\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://tess.elixir-europe.org/events/introduction-to-r-for-biologists-online\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating http://159.149.160.88/pscan_chip_dev/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://hamap.expasy.org/cgi-bin/unirule/unirule_browse.cgi\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://bridgedb.github.io/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://scholia.toolforge.org/gene/Q18030793\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://zbmed.github.io/damalos/docs/2020.html\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://rdmkit.elixir-europe.org/human_data.html\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://nanocommons.github.io/tutorials/enteringData\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://www.ebi.ac.uk/chembl/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://www.proteinatlas.org/\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://prosite.expasy.org\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://identifiers.org/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://bioinformatics.ca/workshops-all/2021-infectious-disease-epidemiology-analysis/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://tess.elixir-europe.org/events/1st-international-conference-on-fair-digital-objects-fdo2022\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://www.omicsdi.org/#/dataset/arrayexpress-repository/E-MTAB-6848\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://bmrb.io/data_library/summary/index.php?bmrbId=30309\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://pcddb.cryst.bbk.ac.uk/\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://disprot.org/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://nanocommons.github.io/specifications/jrc/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://www.ebi.ac.uk/pdbe/entry/pdb/5hbi/protein/1\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://www.metanetx.org/chem_info/MNXM680\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://pairedomicsdata.bioinformatics.nl/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating http://159.149.160.88/pscan/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://datamed.org/display-item.php?repository=0006&id=59139ef65152c62a9fc18ff7\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error while validating http://phenpath.biocomp.unibo.it/phenpath/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://www.guidetopharmacology.org/coronavirus.jsp\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating http://159.149.160.88/cscan\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://string-db.org/network/9606.ENSP00000379258\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://www.chd7.org/\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://deb-central.org/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://www.guidetopharmacology.org/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://zbmed.github.io/damalos/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://cells.ebisc.org/BIHi006-D\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://datacatalog.elixir-luxembourg.org/\n",
      "[Errno Expecting value] <html>\n",
      "  <head>\n",
      "    <title>Internal Server Error</title>\n",
      "  </head>\n",
      "  <body>\n",
      "    <h1><p>Internal Server Error</p></h1>\n",
      "    \n",
      "  </body>\n",
      "</html>\n",
      ": 0\n",
      "Error while validating https://cancer.sanger.ac.uk/cosmic/\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://ega-archive.org/\n",
      "('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
      "Error while validating https://www.sib.swiss/training/course/20230426_DOCK\n",
      "('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))\n",
      "Error while validating https://galaxyproject.org/events/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fgalaxyproject.org%2Fevents%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.sib.swiss/training/course/20221123_OPEMP\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.sib.swiss%2Ftraining%2Fcourse%2F20221123_OPEMP (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604be0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating http://phenpath.biocomp.unibo.it/cgi-bin/phenpath/ppDB.py\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=http%3A%2F%2Fphenpath.biocomp.unibo.it%2Fcgi-bin%2Fphenpath%2FppDB.py (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://workflowhub.eu/people/9\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fworkflowhub.eu%2Fpeople%2F9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160512b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating http://itsonedb.cloud.ba.infn.it/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=http%3A%2F%2Fitsonedb.cloud.ba.infn.it%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1606151f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://inpn.mnhn.fr/espece/cd_nom/60878/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Finpn.mnhn.fr%2Fespece%2Fcd_nom%2F60878%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://fairsharing.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Ffairsharing.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d520>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.ebi.ac.uk/interpro/entry/InterPro/IPR015252/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.ebi.ac.uk%2Finterpro%2Fentry%2FInterPro%2FIPR015252%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://bgee.org/?page=species&amp;species_id=9606#expr-calls\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fbgee.org%2F%3Fpage%3Dspecies%26amp%3Bspecies_id%3D9606%23expr-calls (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615c70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://enzyme.expasy.org/EC/1.1.3.-\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fenzyme.expasy.org%2FEC%2F1.1.3.- (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://bigcat-um.github.io/BiGCaT-Teaching/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fbigcat-um.github.io%2FBiGCaT-Teaching%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160512eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://bio.tools/covidmine\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fbio.tools%2Fcovidmine (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://bar.biocomp.unibo.it/bar3/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fbar.biocomp.unibo.it%2Fbar3%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d130>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://pcddb.cryst.bbk.ac.uk/deposit/CD0000031000\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fpcddb.cryst.bbk.ac.uk%2Fdeposit%2FCD0000031000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://bioregistry.io/registry/hgnc\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fbioregistry.io%2Fregistry%2Fhgnc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1606049a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://nanocommons.github.io/datasets/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fnanocommons.github.io%2Fdatasets%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604b80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating http://edgar.biocomp.unibo.it/cgi-bin/gene_disease_db/gene.py?gene=A2M\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=http%3A%2F%2Fedgar.biocomp.unibo.it%2Fcgi-bin%2Fgene_disease_db%2Fgene.py%3Fgene%3DA2M (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://bridgedb.github.io/data/gene_database/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fbridgedb.github.io%2Fdata%2Fgene_database%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160512b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://search.data.enanomapper.net/about/enanomapper/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fsearch.data.enanomapper.net%2Fabout%2Fenanomapper%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://training.galaxyproject.org/training-material/hall-of-fame/hexylena/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Ftraining.galaxyproject.org%2Ftraining-material%2Fhall-of-fame%2Fhexylena%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060de50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating http://www.ebi.ac.uk/pdbe/entry/pdb/4a7l\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=http%3A%2F%2Fwww.ebi.ac.uk%2Fpdbe%2Fentry%2Fpdb%2F4a7l (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://modelarchive.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fmodelarchive.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615940>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://swissmodel.expasy.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fswissmodel.expasy.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating http://mvid-central.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=http%3A%2F%2Fmvid-central.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615070>: Failed to establish a new connection: [Errno 61] Connection refused'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error while validating https://synbiohub.org/public/igem/BBa_K165005/1\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fsynbiohub.org%2Fpublic%2Figem%2FBBa_K165005%2F1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d850>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:37133\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.genenames.org%2Fdata%2Fgene-symbol-report%2F%23%21%2Fhgnc_id%2FHGNC%3A37133 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://proteinensemble.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fproteinensemble.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160512ee0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.france-bioinformatique.fr/en/evenements_upcoming\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.france-bioinformatique.fr%2Fen%2Fevenements_upcoming (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604b50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://h2020-riskgone.github.io/riskgone-materials/identifiers_and_guidance.html\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fh2020-riskgone.github.io%2Friskgone-materials%2Fidentifiers_and_guidance.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1606049a0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.gbif.org/dataset/c0cc29de-f49f-4b66-b4ec-c83afbb7101d\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.gbif.org%2Fdataset%2Fc0cc29de-f49f-4b66-b4ec-c83afbb7101d (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://enanomapper.github.io/tutorials/Entering_and_analysing_nano_safety_data/readme.html\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fenanomapper.github.io%2Ftutorials%2FEntering_and_analysing_nano_safety_data%2Freadme.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604910>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://biopragmatics.github.io/bioversions/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fbiopragmatics.github.io%2Fbioversions%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1605122b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.gbif.org/species/5220113\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.gbif.org%2Fspecies%2F5220113 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060dfd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.ebi.ac.uk/interpro/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.ebi.ac.uk%2Finterpro%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060de80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.ebi.ac.uk/training/events/metagenomics-bioinformatics-2022/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.ebi.ac.uk%2Ftraining%2Fevents%2Fmetagenomics-bioinformatics-2022%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.genenames.org/#data-catalog\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.genenames.org%2F%23data-catalog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615f70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://disprot.org/DP00086r026\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fdisprot.org%2FDP00086r026 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1606157f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://ippidb.pasteur.fr/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fippidb.pasteur.fr%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615100>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://tess.elixir-europe.org/materials/hands-on-for-exome-sequencing-data-analysis-for-diagnosing-a-genetic-disease-tutorial\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Ftess.elixir-europe.org%2Fmaterials%2Fhands-on-for-exome-sequencing-data-analysis-for-diagnosing-a-genetic-disease-tutorial (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060de80>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.metanetx.org/ftp/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.metanetx.org%2Fftp%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060dc70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://wikipathways.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwikipathways.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160512190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://mint.bio.uniroma2.it/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fmint.bio.uniroma2.it%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604310>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://humanmine.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fhumanmine.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604580>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL59/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.ebi.ac.uk%2Fchembl%2Fcompound_report_card%2FCHEMBL59%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1606044f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=141189&lng=en\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.orpha.net%2Fconsor%2Fcgi-bin%2FOC_Exp.php%3FExpert%3D141189%26lng%3Den (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error while validating http://\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=http%3A%2F%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x112819550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://synbiohub.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fsynbiohub.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://pippa.psb.ugent.be/pippa_experiments/consult_experiment_basic_info/55\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fpippa.psb.ugent.be%2Fpippa_experiments%2Fconsult_experiment_basic_info%2F55 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060df70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://bioschemas.org/tutorials/what_why_bioschemas\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fbioschemas.org%2Ftutorials%2Fwhat_why_bioschemas (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615040>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.guidetopharmacology.org/GRAC/LigandDisplayForward?ligandId=8299\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.guidetopharmacology.org%2FGRAC%2FLigandDisplayForward%3FligandId%3D8299 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1606158e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.html\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Ftraining.galaxyproject.org%2Ftraining-material%2Ftopics%2Fintroduction%2Ftutorials%2Fgalaxy-intro-101-everyone%2Ftutorial.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1606158e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.ensembl.org/id/ENSG00000139618\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.ensembl.org%2Fid%2FENSG00000139618 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://mobidb.org/P04637\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fmobidb.org%2FP04637 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060da60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.opalesurfcasting.net/connaissances/faune-et-flore/le-saumon-de-l-atlantique-salmo-salar.html\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.opalesurfcasting.net%2Fconnaissances%2Ffaune-et-flore%2Fle-saumon-de-l-atlantique-salmo-salar.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060dc70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.ebi.ac.uk/biosamples/samples/SAMEA491372\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.ebi.ac.uk%2Fbiosamples%2Fsamples%2FSAMEA491372 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160512340>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://bioschemas.org/meetings/2022-01_SWAT4HCLS_leiden\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fbioschemas.org%2Fmeetings%2F2022-01_SWAT4HCLS_leiden (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604a00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://bgee.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fbgee.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604760>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://corkoakdb.org/gene/13014\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fcorkoakdb.org%2Fgene%2F13014 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160512b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://pairedomicsdata.bioinformatics.nl/projects/d0f1add5-5b16-4f78-9b93-0d1d9c9bcb59.1\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fpairedomicsdata.bioinformatics.nl%2Fprojects%2Fd0f1add5-5b16-4f78-9b93-0d1d9c9bcb59.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d5e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.ebi.ac.uk/biosamples/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.ebi.ac.uk%2Fbiosamples%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060da60>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.metanetx.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.metanetx.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604eb0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://hamap.expasy.org/archaea.html\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fhamap.expasy.org%2Farchaea.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604c40>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://flymine.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fflymine.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615190>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://scholia.toolforge.org/protein/Q424728\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fscholia.toolforge.org%2Fprotein%2FQ424728 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1606158e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://reactome.org/content/detail/R-HSA-449147\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Freactome.org%2Fcontent%2Fdetail%2FR-HSA-449147 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615d90>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://disprot.org/DP00086\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fdisprot.org%2FDP00086 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://zbmed-semtec.github.io/dome-galaxy-training/docs/DOME.html\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fzbmed-semtec.github.io%2Fdome-galaxy-training%2Fdocs%2FDOME.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060df70>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://string-db.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fstring-db.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060dcd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://massbank.eu/MassBank/RecordDisplay?id=LQB00001&dsn=RIKEN_IMS\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fmassbank.eu%2FMassBank%2FRecordDisplay%3Fid%3DLQB00001%26dsn%3DRIKEN_IMS (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating http://edgar.biocomp.unibo.it/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=http%3A%2F%2Fedgar.biocomp.unibo.it%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604b20>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://datacatalog.elixir-luxembourg.org/e/dataset/924dfe7a-71e8-11eb-bafe-3e22fbb3883f\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fdatacatalog.elixir-luxembourg.org%2Fe%2Fdataset%2F924dfe7a-71e8-11eb-bafe-3e22fbb3883f (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160512c10>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.ensembl.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.ensembl.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160512ca0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.birmingham.ac.uk/facilities/metabolomics-training-centre/courses/q-exactive.aspx\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.birmingham.ac.uk%2Ffacilities%2Fmetabolomics-training-centre%2Fcourses%2Fq-exactive.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.covid19dataportal.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.covid19dataportal.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604e50>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.genenames.org/data/gene-symbol-report/#data-set\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.genenames.org%2Fdata%2Fgene-symbol-report%2F%23data-set (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060dcd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.elixir-europe.org/events/biohackathon-2018-paris\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.elixir-europe.org%2Fevents%2Fbiohackathon-2018-paris (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d550>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating http://www.cathdb.info\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=http%3A%2F%2Fwww.cathdb.info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615cd0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://psnpbind.org/protein/1owh\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fpsnpbind.org%2Fprotein%2F1owh (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1606159d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://bgee.org/?page=gene&gene_id=ENSG00000274928\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fbgee.org%2F%3Fpage%3Dgene%26gene_id%3DENSG00000274928 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615820>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://proteinensemble.org/PED00014\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fproteinensemble.org%2FPED00014 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160615a00>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://aip.fipapatients.org/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Faip.fipapatients.org%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d4f0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://ega-archive.org/datasets/EGAD00000000001\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fega-archive.org%2Fdatasets%2FEGAD00000000001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x16060d5e0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n",
      "Error while validating https://www.ebi.ac.uk/Tools/hmmer/search/phmmer\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fwww.ebi.ac.uk%2FTools%2Fhmmer%2Fsearch%2Fphmmer (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x160604ac0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error while validating https://workflowhub.eu/\n",
      "HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fworkflowhub.eu%2F (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1606045b0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Empty DataFrame\n",
       "Columns: []\n",
       "Index: []"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "rows = []\n",
    "#print(lds)\n",
    "for ld in tqdm(lds):\n",
    "    try: \n",
    "        bs_valid = check_bioschemas(ld)\n",
    "        for entity in bs_valid.keys():\n",
    "            row = {\"Bioschemas Live Deploy URL\": ld}  \n",
    "            row[\"Evaluated entity\"] = entity\n",
    "            row[\"Reference profile\"] = bs_valid[entity][\"ref_profile\"]\n",
    "            row[\"Is valid\"] = bs_valid[entity][\"conforms\"]\n",
    "            row[\"Nb errors\"] = len(bs_valid[entity][\"errors\"])\n",
    "            row[\"Nb warnings\"] = len(bs_valid[entity][\"warnings\"])\n",
    "            row[\"Is the latest profile\"] = bs_valid[entity][\"latest_profile\"]\n",
    "            row[\"Is deprecated profile\"] = bs_valid[entity][\"deprecated\"]\n",
    "            rows.append(row)\n",
    "            break\n",
    "    except Exception as e: \n",
    "        print(f\"Error while validating {ld}\")\n",
    "        print(e)\n",
    "df2 = pd.DataFrame.from_records(rows)\n",
    "#df2.to_csv(\"bioschemas_validation.csv\")\n",
    "df2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "c59c5820",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/markdown": [
       "<i class=\"fa fa-camera\"></i>"
      ],
      "text/plain": [
       "<IPython.core.display.Markdown object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from IPython.display import display, Markdown, Latex\n",
    "my_md = '<i class=\"fa fa-camera\"></i>'\n",
    "display(Markdown(my_md))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "503d0126",
   "metadata": {},
   "outputs": [],
   "source": [
    "md1 = \"\"\"\n",
    "{\"@id\": \"_:N0b2cabb67c8a461a8c1c84367ef89fb1\", \"http://www.w3.org/1999/xhtml/vocab#role\": [{\"@id\": \"http://www.w3.org/1999/xhtml/vocab#img\"}]}\n",
    "\"\"\"\n",
    "\n",
    "md2 = \"\"\"\n",
    "{\"type\": \"http://schema.org/Organization\", \"properties\": {\"logo\": \"http://bioschemas.org/assets/img/square_logo2.png\", \"url\": \"http://bioschemas.org\", \"email\": \"enquiries@bioschemas.org\", \"name\": \"Bioschemas Community\"}}\n",
    "\"\"\"\n",
    "\n",
    "md3 = \"\"\"\n",
    "\n",
    "\"\"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "f19925e1",
   "metadata": {},
   "outputs": [],
   "source": [
    "#live_deploys_remote_file = \"https://raw.githubusercontent.com/BioSchemas/bioschemas.github.io/master/_data/live_deployments.json\"\n",
    "#res = requests.get(live_deploys_remote_file)\n",
    "#live_deploys = res.json()\n",
    "#print(json.dumps(live_deploys, indent=True))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "e2b87c87",
   "metadata": {},
   "outputs": [
    {
     "ename": "ConnectionError",
     "evalue": "HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fmobidb.org (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10b0bee20>: Failed to establish a new connection: [Errno 61] Connection refused'))",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mConnectionRefusedError\u001b[0m                    Traceback (most recent call last)",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/urllib3/connection.py:174\u001b[0m, in \u001b[0;36mHTTPConnection._new_conn\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    173\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 174\u001b[0m     conn \u001b[38;5;241m=\u001b[39m \u001b[43mconnection\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcreate_connection\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    175\u001b[0m \u001b[43m        \u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_dns_host\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mport\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mextra_kw\u001b[49m\n\u001b[1;32m    176\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    178\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m SocketTimeout:\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/urllib3/util/connection.py:95\u001b[0m, in \u001b[0;36mcreate_connection\u001b[0;34m(address, timeout, source_address, socket_options)\u001b[0m\n\u001b[1;32m     94\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m err \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m---> 95\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m err\n\u001b[1;32m     97\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m socket\u001b[38;5;241m.\u001b[39merror(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mgetaddrinfo returns an empty list\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/urllib3/util/connection.py:85\u001b[0m, in \u001b[0;36mcreate_connection\u001b[0;34m(address, timeout, source_address, socket_options)\u001b[0m\n\u001b[1;32m     84\u001b[0m     sock\u001b[38;5;241m.\u001b[39mbind(source_address)\n\u001b[0;32m---> 85\u001b[0m \u001b[43msock\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnect\u001b[49m\u001b[43m(\u001b[49m\u001b[43msa\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     86\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m sock\n",
      "\u001b[0;31mConnectionRefusedError\u001b[0m: [Errno 61] Connection refused",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mNewConnectionError\u001b[0m                        Traceback (most recent call last)",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/urllib3/connectionpool.py:703\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    702\u001b[0m \u001b[38;5;66;03m# Make the request on the httplib connection object.\u001b[39;00m\n\u001b[0;32m--> 703\u001b[0m httplib_response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_make_request\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    704\u001b[0m \u001b[43m    \u001b[49m\u001b[43mconn\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    705\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    706\u001b[0m \u001b[43m    \u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    707\u001b[0m \u001b[43m    \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout_obj\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    708\u001b[0m \u001b[43m    \u001b[49m\u001b[43mbody\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mbody\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    709\u001b[0m \u001b[43m    \u001b[49m\u001b[43mheaders\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    710\u001b[0m \u001b[43m    \u001b[49m\u001b[43mchunked\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mchunked\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    711\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    713\u001b[0m \u001b[38;5;66;03m# If we're going to release the connection in ``finally:``, then\u001b[39;00m\n\u001b[1;32m    714\u001b[0m \u001b[38;5;66;03m# the response doesn't need to know about the connection. Otherwise\u001b[39;00m\n\u001b[1;32m    715\u001b[0m \u001b[38;5;66;03m# it will also try to release it and we'll have a double-release\u001b[39;00m\n\u001b[1;32m    716\u001b[0m \u001b[38;5;66;03m# mess.\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/urllib3/connectionpool.py:386\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    385\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 386\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_validate_conn\u001b[49m\u001b[43m(\u001b[49m\u001b[43mconn\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    387\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (SocketTimeout, BaseSSLError) \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m    388\u001b[0m     \u001b[38;5;66;03m# Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/urllib3/connectionpool.py:1040\u001b[0m, in \u001b[0;36mHTTPSConnectionPool._validate_conn\u001b[0;34m(self, conn)\u001b[0m\n\u001b[1;32m   1039\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mgetattr\u001b[39m(conn, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124msock\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28;01mNone\u001b[39;00m):  \u001b[38;5;66;03m# AppEngine might not have  `.sock`\u001b[39;00m\n\u001b[0;32m-> 1040\u001b[0m     \u001b[43mconn\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnect\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1042\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m conn\u001b[38;5;241m.\u001b[39mis_verified:\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/urllib3/connection.py:358\u001b[0m, in \u001b[0;36mHTTPSConnection.connect\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    356\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mconnect\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[1;32m    357\u001b[0m     \u001b[38;5;66;03m# Add certificate verification\u001b[39;00m\n\u001b[0;32m--> 358\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msock \u001b[38;5;241m=\u001b[39m conn \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_new_conn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    359\u001b[0m     hostname \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhost\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/urllib3/connection.py:186\u001b[0m, in \u001b[0;36mHTTPConnection._new_conn\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    185\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m SocketError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m--> 186\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m NewConnectionError(\n\u001b[1;32m    187\u001b[0m         \u001b[38;5;28mself\u001b[39m, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mFailed to establish a new connection: \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m%\u001b[39m e\n\u001b[1;32m    188\u001b[0m     )\n\u001b[1;32m    190\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m conn\n",
      "\u001b[0;31mNewConnectionError\u001b[0m: <urllib3.connection.HTTPSConnection object at 0x10b0bee20>: Failed to establish a new connection: [Errno 61] Connection refused",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mMaxRetryError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/requests/adapters.py:440\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    439\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m chunked:\n\u001b[0;32m--> 440\u001b[0m     resp \u001b[38;5;241m=\u001b[39m \u001b[43mconn\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43murlopen\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    441\u001b[0m \u001b[43m        \u001b[49m\u001b[43mmethod\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    442\u001b[0m \u001b[43m        \u001b[49m\u001b[43murl\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    443\u001b[0m \u001b[43m        \u001b[49m\u001b[43mbody\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mbody\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    444\u001b[0m \u001b[43m        \u001b[49m\u001b[43mheaders\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    445\u001b[0m \u001b[43m        \u001b[49m\u001b[43mredirect\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m    446\u001b[0m \u001b[43m        \u001b[49m\u001b[43massert_same_host\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m    447\u001b[0m \u001b[43m        \u001b[49m\u001b[43mpreload_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m    448\u001b[0m \u001b[43m        \u001b[49m\u001b[43mdecode_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[1;32m    449\u001b[0m \u001b[43m        \u001b[49m\u001b[43mretries\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmax_retries\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    450\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\n\u001b[1;32m    451\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    453\u001b[0m \u001b[38;5;66;03m# Send the request.\u001b[39;00m\n\u001b[1;32m    454\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/urllib3/connectionpool.py:785\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    783\u001b[0m     e \u001b[38;5;241m=\u001b[39m ProtocolError(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mConnection aborted.\u001b[39m\u001b[38;5;124m\"\u001b[39m, e)\n\u001b[0;32m--> 785\u001b[0m retries \u001b[38;5;241m=\u001b[39m \u001b[43mretries\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mincrement\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    786\u001b[0m \u001b[43m    \u001b[49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43merror\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43me\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m_pool\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m_stacktrace\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43msys\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexc_info\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;241;43m2\u001b[39;49m\u001b[43m]\u001b[49m\n\u001b[1;32m    787\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    788\u001b[0m retries\u001b[38;5;241m.\u001b[39msleep()\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/urllib3/util/retry.py:592\u001b[0m, in \u001b[0;36mRetry.increment\u001b[0;34m(self, method, url, response, error, _pool, _stacktrace)\u001b[0m\n\u001b[1;32m    591\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m new_retry\u001b[38;5;241m.\u001b[39mis_exhausted():\n\u001b[0;32m--> 592\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m MaxRetryError(_pool, url, error \u001b[38;5;129;01mor\u001b[39;00m ResponseError(cause))\n\u001b[1;32m    594\u001b[0m log\u001b[38;5;241m.\u001b[39mdebug(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIncremented Retry for (url=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m): \u001b[39m\u001b[38;5;132;01m%r\u001b[39;00m\u001b[38;5;124m\"\u001b[39m, url, new_retry)\n",
      "\u001b[0;31mMaxRetryError\u001b[0m: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fmobidb.org (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10b0bee20>: Failed to establish a new connection: [Errno 61] Connection refused'))",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mConnectionError\u001b[0m                           Traceback (most recent call last)",
      "Input \u001b[0;32mIn [8]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m mobidb_valid \u001b[38;5;241m=\u001b[39m \u001b[43mcheck_bioschemas\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mhttps://mobidb.org\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28mprint\u001b[39m(json\u001b[38;5;241m.\u001b[39mdumps(mobidb_valid, indent\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m))\n",
      "Input \u001b[0;32mIn [2]\u001b[0m, in \u001b[0;36mcheck_bioschemas\u001b[0;34m(url)\u001b[0m\n\u001b[1;32m     62\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mcheck_bioschemas\u001b[39m(url):  \n\u001b[1;32m     63\u001b[0m     \u001b[38;5;66;03m#FC_bs_valid = \"https://fair-checker.france-bioinformatique.fr/api/inspect/bioschemas_validation\"\u001b[39;00m\n\u001b[1;32m     64\u001b[0m     \u001b[38;5;66;03m#FC_bs_valid = \"https://fair-checker.france-bioinformatique.fr/api/inspect/bioschemas_validation_by_conformsto\"\u001b[39;00m\n\u001b[1;32m     65\u001b[0m     FC_bs_valid \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhttps://localhost:5000/api/inspect/bioschemas_validation_by_conformsto\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m---> 66\u001b[0m     res \u001b[38;5;241m=\u001b[39m \u001b[43mrequests\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\u001b[43murl\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mFC_bs_valid\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mparams\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m{\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43murl\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[43m}\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     67\u001b[0m     \u001b[38;5;66;03m#print(res.text)\u001b[39;00m\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m#try:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m#    print(json.dumps(res.json(), indent=True))\u001b[39;00m\n\u001b[1;32m     70\u001b[0m     \u001b[38;5;66;03m#except Exception as e:\u001b[39;00m\n\u001b[1;32m     71\u001b[0m     \u001b[38;5;66;03m#    print(e)\u001b[39;00m\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m res\u001b[38;5;241m.\u001b[39mjson()\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/requests/api.py:75\u001b[0m, in \u001b[0;36mget\u001b[0;34m(url, params, **kwargs)\u001b[0m\n\u001b[1;32m     64\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mget\u001b[39m(url, params\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m     65\u001b[0m     \u001b[38;5;124mr\u001b[39m\u001b[38;5;124;03m\"\"\"Sends a GET request.\u001b[39;00m\n\u001b[1;32m     66\u001b[0m \n\u001b[1;32m     67\u001b[0m \u001b[38;5;124;03m    :param url: URL for the new :class:`Request` object.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     72\u001b[0m \u001b[38;5;124;03m    :rtype: requests.Response\u001b[39;00m\n\u001b[1;32m     73\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[0;32m---> 75\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mrequest\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mget\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mparams\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mparams\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/requests/api.py:61\u001b[0m, in \u001b[0;36mrequest\u001b[0;34m(method, url, **kwargs)\u001b[0m\n\u001b[1;32m     57\u001b[0m \u001b[38;5;66;03m# By using the 'with' statement we are sure the session is closed, thus we\u001b[39;00m\n\u001b[1;32m     58\u001b[0m \u001b[38;5;66;03m# avoid leaving sockets open which can trigger a ResourceWarning in some\u001b[39;00m\n\u001b[1;32m     59\u001b[0m \u001b[38;5;66;03m# cases, and look like a memory leak in others.\u001b[39;00m\n\u001b[1;32m     60\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m sessions\u001b[38;5;241m.\u001b[39mSession() \u001b[38;5;28;01mas\u001b[39;00m session:\n\u001b[0;32m---> 61\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43msession\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmethod\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43murl\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/requests/sessions.py:529\u001b[0m, in \u001b[0;36mSession.request\u001b[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[1;32m    524\u001b[0m send_kwargs \u001b[38;5;241m=\u001b[39m {\n\u001b[1;32m    525\u001b[0m     \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mtimeout\u001b[39m\u001b[38;5;124m'\u001b[39m: timeout,\n\u001b[1;32m    526\u001b[0m     \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mallow_redirects\u001b[39m\u001b[38;5;124m'\u001b[39m: allow_redirects,\n\u001b[1;32m    527\u001b[0m }\n\u001b[1;32m    528\u001b[0m send_kwargs\u001b[38;5;241m.\u001b[39mupdate(settings)\n\u001b[0;32m--> 529\u001b[0m resp \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mprep\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43msend_kwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    531\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m resp\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/requests/sessions.py:645\u001b[0m, in \u001b[0;36mSession.send\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    642\u001b[0m start \u001b[38;5;241m=\u001b[39m preferred_clock()\n\u001b[1;32m    644\u001b[0m \u001b[38;5;66;03m# Send the request\u001b[39;00m\n\u001b[0;32m--> 645\u001b[0m r \u001b[38;5;241m=\u001b[39m \u001b[43madapter\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    647\u001b[0m \u001b[38;5;66;03m# Total elapsed time of the request (approximately)\u001b[39;00m\n\u001b[1;32m    648\u001b[0m elapsed \u001b[38;5;241m=\u001b[39m preferred_clock() \u001b[38;5;241m-\u001b[39m start\n",
      "File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/requests/adapters.py:519\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    515\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(e\u001b[38;5;241m.\u001b[39mreason, _SSLError):\n\u001b[1;32m    516\u001b[0m         \u001b[38;5;66;03m# This branch is for urllib3 v1.22 and later.\u001b[39;00m\n\u001b[1;32m    517\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m SSLError(e, request\u001b[38;5;241m=\u001b[39mrequest)\n\u001b[0;32m--> 519\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mConnectionError\u001b[39;00m(e, request\u001b[38;5;241m=\u001b[39mrequest)\n\u001b[1;32m    521\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m ClosedPoolError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m    522\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mConnectionError\u001b[39;00m(e, request\u001b[38;5;241m=\u001b[39mrequest)\n",
      "\u001b[0;31mConnectionError\u001b[0m: HTTPSConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/inspect/bioschemas_validation_by_conformsto?url=https%3A%2F%2Fmobidb.org (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10b0bee20>: Failed to establish a new connection: [Errno 61] Connection refused'))"
     ]
    }
   ],
   "source": [
    "mobidb_valid = check_bioschemas(\"https://mobidb.org\")\n",
    "print(json.dumps(mobidb_valid, indent=True))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "94e29a4a",
   "metadata": {},
   "outputs": [
    {
     "ename": "BadSyntax",
     "evalue": "at line 4 of <>:\nBad syntax (expected '.' or '}' or ']' at end of statement) at ^ in:\n\"b'<!DOCTYPE html>\\n<html lang=\"en\">\\n<html>\\n  '^b'<head>\\n  <meta charset=\"utf-8\">\\n  <meta http-equiv=\"X-UA-Com'...\"",
     "output_type": "error",
     "traceback": [
      "Traceback \u001b[0;36m(most recent call last)\u001b[0m:\n",
      "  File \u001b[1;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3361\u001b[0m in \u001b[1;35mrun_code\u001b[0m\n    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  Input \u001b[1;32mIn [9]\u001b[0m in \u001b[1;35m<cell line: 2>\u001b[0m\n    g.parse(\"http://bioschemas.org/\", format=\"n3\")\n",
      "  File \u001b[1;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/rdflib/graph.py:1977\u001b[0m in \u001b[1;35mparse\u001b[0m\n    context.parse(source, publicID=publicID, format=format, **args)\n",
      "  File \u001b[1;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/rdflib/graph.py:1339\u001b[0m in \u001b[1;35mparse\u001b[0m\n    raise se\n",
      "  File \u001b[1;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/rdflib/graph.py:1330\u001b[0m in \u001b[1;35mparse\u001b[0m\n    parser.parse(source, self, **args)\n",
      "  File \u001b[1;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/rdflib/plugins/parsers/notation3.py:1977\u001b[0m in \u001b[1;35mparse\u001b[0m\n    TurtleParser.parse(self, source, conj_graph, encoding, turtle=False)\n",
      "  File \u001b[1;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/rdflib/plugins/parsers/notation3.py:1943\u001b[0m in \u001b[1;35mparse\u001b[0m\n    p.loadStream(stream)\n",
      "  File \u001b[1;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/rdflib/plugins/parsers/notation3.py:454\u001b[0m in \u001b[1;35mloadStream\u001b[0m\n    return self.loadBuf(stream.read())  # Not ideal\n",
      "  File \u001b[1;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/rdflib/plugins/parsers/notation3.py:460\u001b[0m in \u001b[1;35mloadBuf\u001b[0m\n    self.feed(buf)\n",
      "  File \u001b[1;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/rdflib/plugins/parsers/notation3.py:486\u001b[0m in \u001b[1;35mfeed\u001b[0m\n    i = self.directiveOrStatement(s, j)\n",
      "  File \u001b[1;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/rdflib/plugins/parsers/notation3.py:508\u001b[0m in \u001b[1;35mdirectiveOrStatement\u001b[0m\n    return self.checkDot(argstr, j)\n",
      "  File \u001b[1;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/rdflib/plugins/parsers/notation3.py:1169\u001b[0m in \u001b[1;35mcheckDot\u001b[0m\n    self.BadSyntax(argstr, j, \"expected '.' or '}' or ']' at end of statement\")\n",
      "\u001b[0;36m  File \u001b[0;32m~/miniconda3/envs/fair-checker/lib/python3.9/site-packages/rdflib/plugins/parsers/notation3.py:1666\u001b[0;36m in \u001b[0;35mBadSyntax\u001b[0;36m\u001b[0m\n\u001b[0;31m    raise BadSyntax(self._thisDoc, self.lines, argstr, i, msg)\u001b[0m\n",
      "\u001b[0;36m  File \u001b[0;32m<string>\u001b[0;36m\u001b[0m\n\u001b[0;31mBadSyntax\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "g = ConjunctiveGraph()\n",
    "g.parse(\"http://bioschemas.org/\", format=\"n3\")\n",
    "#print(g.serialize(format=\"turtle\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f7b46364",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
